version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faker
    versions:
    - 5.8.0
    - 6.0.0
    - 6.1.1
    - 6.3.0
    - 6.4.1
    - 6.5.2
    - 6.6.1
    - 7.0.1
  - dependency-name: django-axes
    versions:
    - 5.12.0
    - 5.13.0
    - 5.13.1
  - dependency-name: django
    versions:
    - 3.1.*
    - 4.0.*
    - 4.1.*
    - 5.0.*
    - 5.1.*
  - dependency-name: pygments
    versions:
    - 2.7.4
  - dependency-name: pytz
    versions:
    - "2020.5"
