language: python

cache: pip

python:
#    - "2.7.9"
    - "3.6.7"

services:
    - postgresql

env:
  global:
    - SECRET_KEY_RAZ="test§$%§$§%"
    - DJANGO_SETTINGS_MODULE="ionescu77v2Project.settings.travis"
  matrix:
    include:
      - name: Django 1.11
          - DJANGO="Django<1.12"
      - name: Django 2.2
          - DJANGO="Django<2.3"
      - name: Django 3.1
          - DJANGO="Django<3.2"

# command to install dependencies
install:
    - pip install "$DJANGO"
    # exclude Django from requirements
    - sed -i '/^Django==/d' requirements/base.txt
    - pip install -r requirements/test.txt

matrix:
  fast_finish: true

before_script:
    - psql -c "CREATE DATABASE travisci;" -U postgres
    - cd src; python manage.py makemigrations; python manage.py migrate

# command to run tests
script:
    - coverage run --include="blogengine/*" --omit="blogengine/migrations/*" manage.py test blogengine

after_success:
    coveralls
