language: python

cache: pip

python:
#    - "2.7.9"
    - "3.6.7"

services:
    - postgresql

jobs:
  include:
  - name: "Django 1.11"
    env:
        - SECRET_KEY_RAZ="test§$%§$§%"
        - DJANGO_SETTINGS_MODULE="ionescu77v2Project.settings.travis"
        - DJANGO="Django<1.12"
  - name: "Django 2.2"
    env:
        - SECRET_KEY_RAZ="test§$%§$§%"
        - DJANGO_SETTINGS_MODULE="ionescu77v2Project.settings.travis"
        - DJANGO="Django<2.3"
  allow_failures:
  - name: "Django 3.1"
    env:
        - SECRET_KEY_RAZ="test§$%§$§%"
        - DJANGO_SETTINGS_MODULE="ionescu77v2Project.settings.travis"
        - DJANGO="Django<3.2"

before_script:
    - psql -c "CREATE DATABASE travisci;" -U postgres
    - echo $DJANGO

# command to run tests
script:
    - pip install "$DJANGO"
    # exclude Django from requirements
    - sed -i '/^Django==/d' requirements/base.txt
    - pip install -r requirements/test.txt
    - cd src; python manage.py makemigrations; python manage.py migrate
    - coverage run --include="blogengine/*" --omit="blogengine/migrations/*" manage.py test blogengine

after_success:
    - coverage run --include="blogengine/*" --omit="blogengine/migrations/*" manage.py test blogengine
    - coveralls
